name: My Release Workflow

#trigger
on:
  push:
    branches:
    - "release/*"

#jobs in the workflow
jobs:
 #job name
  myReleaseWorkflow:
    #OS that this workflow will be running on
    runs-on: ubuntu-latest

    #list of steps to perform task
    steps:
    - name: Echo the branch name
      run: echo "Current branch - ${{ github.ref_name }}"
    - name: Checkout the correct branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}