name: My Workflow

#trigger
on:
- push:
  branches:
  - 'release/*'

#jobs in the workflow
jobs:
 #job name
 myWorkflow:
    #OS that this workflow will be running on
    runs-on: ubuntu-latest

    #list of steps to perform task
    steps:
    - name: Checkout the correct branch
      uses: actions/checkout@v3
      with:
        ref: 'release/*'